CutURL/Models/URLModel.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace CutURL.Models
{
    public class URLModel
    {
        [Required]
        [JsonProperty("orignalurl")]
        public string OriginalURL { get; set; }
        [JsonProperty("shroturl")]
        public string ShortURL { get; set; }
        [JsonIgnore]
        public string CustomURL { get; set; }
    }
}

CutURL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CutURL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CutURL/Controllers/UrlShortnerController.cs
using CutURL.BusinessLayer;
using CutURL.Models;
using CutURL.Entities;
using Newtonsoft.Json;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace CutURL.Controllers
{
    public class UrlShortnerController : Controller
    {
        // GET: UrlShortner
        private IURLManager _manager;

        public UrlShortnerController(IURLManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public ActionResult Index()
        {
            URLModel url = new URLModel();
            return View(url);
        }
        public async Task<ActionResult> Index(URLModel url)
        {
            if (ModelState.IsValid)
            {
                URLDetails shortUrl = await this._manager.ShortenUrl(url.OriginalURL, Request.UserHostAddress);
                url.ShortURL = string.Format("{0}://{1}{2}{3}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"), shortUrl.CustomUrl);
            }
            return View(url);
        }
        public async Task<ActionResult> Click(string segment)
        {
            
            Statistics stat = await this._manager.Click(segment);
            return this.RedirectPermanent(stat.ShortUrl.OrignalUrl);
        }

        public async Task<ActionResult> ShowStats(string segment)
        {
            URLDetails details=null;
            if (ModelState.IsValid)
            {
                details = await _manager.FetchStatistics(segment);
            }
            return View(details);
        }
        public ActionResult GoBack()
        {
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

CutURL/Views/Shared/Error404.cshtml
@{
    ViewBag.Title = "Error 404";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error404</title>
</head>
<body>
    <div class="container-fluid">
        <div class="jumbotron">
            <h1 class="alert-danger" >ERROR</h1>
            <p class="danger">Error 404</p>
        </div>
    </div>
</body>
</html>

CutURL/Views/Shared/Error409.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error409</title>
</head>
<body>
    <div class="container-fluid">
        <div class="jumbotron">
            <h1 class="alert-danger">ERROR</h1>
            <p class="danger">Error 409</p>
        </div>
    </div>
</body>
</html>

CutURL/Views/Shared/Error500.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error500</title>
</head>
<body>
    <div class="container-fluid">
        <div class="jumbotron">
            <h1 class="alert-danger">ERROR</h1>
            <p class="danger">Error 500</p>
        </div>
    </div>
</body>
</html>

CutURL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cut URLs</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Cut Urls Short", "Url", "Index", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.ActionLink("Go Home", "GoBack");
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CutURL/Views/UrlShortner/Index.cshtml
@model CutURL.Models.URLModel

@{
    ViewBag.Title= "Cut URL Home";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1>CUT your URL here</h1>
                <p class="lead">Shorten your url here</p>
            </div>
        </div>
    </div>
    @Html.ValidationSummary();
    @using (Html.BeginForm())
    {
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.TextBoxFor(Model => Model.OriginalURL, new { placeholder = "Orignal URL", @class = "form-control" })
                </div>
                <br />
                <div class="form-group">
                    @Html.TextBoxFor(Model => Model.CustomURL, new { placeholder = "Custom URL", @class = "form-control" })
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
        <div class="row">
            <div class=" col-md-8">
            </div>
            <div class="col-md-4">
                <input id="Submit1" type="submit" value="Cut It" class="btn btn-primary" />
            </div>
        </div>
    }
    @if (!string.IsNullOrEmpty(Model.ShortURL))
    {
        using (Html.BeginForm("ShowStats", "UrlShortner"))
        {
            <br/>
            <div class="row">
                <div class="col-md-5">

                    <div>
                        <h4><a href="@Model.ShortURL" target="_blank">@Model.ShortURL</a></h4>
                        @{ string value = Model.ShortURL.Substring(Model.ShortURL.LastIndexOf('/')+1);}
                        <input type="hidden" name="segment" value="@value" />
                    </div>    
                </div>
                <div class="col-lg-2"></div>
                <div class="col-md-3">
                </div>
                <div class="col-md-2">
                    <input id="Submit2" type="submit" value="Show Statistics" class="btn btn-primary" />
                </div>

            </div>
        }
    }
    </body>
</html>

CutURL/Views/UrlShortner/ShowStats.cshtml
@model CutURL.Entities.URLDetails

@{
    ViewBag.Title = "Details";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowStats</title>
</head>
<body>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h2 style="align-self:center;align-content:center;" class="lead"><a href=@Model.OrignalUrl>@Model.OrignalUrl</a></h2>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row active">
        <div class="col-md-2">
            <h4 style="align-self:center;align-content:center;" class="lead">Created on</h4>
        </div>
        <div class="col-md-2">
            <h4 style="align-self:center;align-content:center;" class="lead">@Model.CreatedOn.ToString()</h4>
        </div>

        <div class="col-md-2">
            <h4 style="align-self:center;align-content:center;" class="lead">Clicks Occured</h4>
        </div>
        <div class="col-md-2 ">
            <h4 style="align-self:center;align-content:center;" class="lead">@Model.ClickCounter</h4>
        </div>
        <div class="col-md-2">
            <h4 style="align-self:center;align-content:center;" class="lead">IP Used for creation</h4>
        </div>
        <div class="col-md-2">
            <h4 style="align-self:center;align-content:center;" class="lead">@Model.Ip</h4>
        </div>
    </div>
    @if (Model.statistics != null)
    {
        foreach (var item in Model.statistics)
        {
            <div class="row active">
                <div class="col-md-3"></div>
                <div class="col-md-3"><h5 style="align-self:center;align-content:center;" class="lead">Clicked On</h5></div>
                <div class="col-md-3"><h5 style="align-self:center;align-content:center;" class="lead">@item.ClickDate.ToString()</h5></div>
                <div class="col-md-3"></div>
            </div>
        }
    }
</body>
</html>